#!/usr/bin/env bash
. "$(dirname "$0")/_/husky.sh"

YELLOW='\033[1;33m'
NO_COLOR='\033[0m'

PNPM_LOCK_CHANGE=0
SCHEMA_CHANGE=0

# Checks if the file "pnpm-lock.yaml" has been modified after the merge
if [ $(git diff --name-only HEAD@{1} HEAD | grep -E "(^pnpm-lock\.yaml)") ]; then
	PNPM_LOCK_CHANGE=1
	echo "\n${YELLOW}⚠️ New dependencies identified. Installing...${NO_COLOR}\n"
	pnpm install
fi
