-- Database backup before image management refactor
-- This file will be populated when the actual backup is run
-- 
-- Run: node scripts/utils/backup-database.js to create actual backup
-- Date: $(date)
-- 
-- Tables to backup:
-- - artworks (with current image fields)
-- - series (with cover_image fields) 
-- - artifacts (with image fields)
-- - series_artworks (relationships)
-- - about_page
-- - user_roles
--
-- IMPORTANT: This backup should be created before applying any migrations
-- to preserve the current state of the image management system